id: P662BB78A
initial_creation_type: input
source_metadata:
  title: Guru Padmasambhava
  language: pt
  description: 'Prayers to the Precious Guru Padmasambhava or Padmākara (padma ''byung
    gnas), the "Lotus-Born", who is credited with establishing Buddhism in Tibet:'
  volume:
    6fe5ab98f69243bc94fa77b19f641a68:
      title: A Synopsis of Guru Padmasambhava’s Life
      parent: Alak Zenkar Pema Ngödrup Rolwe Dorje
    b5ec189e1a294575935120a30ed07126:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Dudjom Rinpoche
    63685d4d20d9433d9224b66dd636fcbf:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Chokgyur Dechen Lingpa
    a1199fe52e8a426598d19c302e002e35:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    ab305f8eb8644ff3b0a8b3c19e480312:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    056e53c4d8ac47eaa47cabfd93ec01a3:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Chokgyur Dechen Lingpa
    7e23278b236747c7b5a5c2b6a48d4316:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    2c240dcd313c4f1ca53b90f854e4e691:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    2ce72f8f304844dea95f71e943317c8c:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    cfa0cd93bd55411cb5c9f608fcce3d9e:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Chokgyur Dechen Lingpa
    76e6408e8b1941058ba3bbf7588595fb:
      title: 'A Garland of Vajra Words: A Prayer to the Guru'
      parent: Dilgo Khyentse Rinpoche
    896fe0b609704c92a3645d8be3014706:
      title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in
        Eight Chapters'
      parent: Dilgo Khyentse Rinpoche
    b9efb7a3dce946ebabf263886f5d030a:
      title: The Prayer to Swiftly Fulfil All Wishes
      parent: Dilgo Khyentse Rinpoche
    fd2afe78a27c4ac2bb5f9201f5c9c883:
      title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
      parent: Dilgo Khyentse Rinpoche
    816fa7994f154a6cb2178f145efaaf2f:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    e4b8b53d521746e28eea62541e0ea527:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    cf17bd8e5b93467dae84fcc8f47c738d:
      title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
      parent: Dodrupchen Jigme Tenpe Nyima
    da564f4b6c874e03b6cd8ae070a9f6ac:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Dodrupchen Jigme Tenpe Nyima
    0fb6ee8f0db047b7b02c8d7b40325de6:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    8e4f648044644c1e847d8e8ac43389ed:
      title: A Prayer to Padmasambhava
      parent: Dudjom Lingpa
    0ffa5c3625fb4e9384704bbbe3bf3fe3:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Dudjom Rinpoche
    0c5e450f7b1c46cc80d395416775d91a:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Dudjom Rinpoche
    c73e9f4f2e0a4d80ac59fe51d88da03a:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Dudjom Rinpoche
    0989ff132eb04fcaa8d6c946d89f5d13:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Dudjom Rinpoche
    d3a4fc1fa3de4e3f8af1c46b03e8f874:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Dudjom Rinpoche
    3ea2d0b20a0b4d82aa1596e69db96c81:
      title: A Prayer to the Precious Guru from Uḍḍiyāna That Spontaneously Fulfils
        All Wishes
      parent: Dzongter Kunzang Nyima
    a63c7c7bcd264db4abee00f01141617e:
      title: 'Cloud Banks of Blessings: A Prayer to Guru Padmasambhava'
      parent: Fifth Dalai Lama
    541934f9fb4549aaad239e4b67c5abd8:
      title: A Yearning Song of Prayer to Invoke the Wisdom Mind of the Compassionate
        Teacher Padmasambhava
      parent: Fourteenth Dalai Lama
    c2971dd69d6b4fb1be3461f271cbdcbd:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    d702783bb74b4044af2858f33969d77b:
      title: Prayer to Orgyen Rinpoche Invoking His Wisdom Mind
      parent: Gönpo Tseten Rinpoche
    49b165e84d4449278c683cf36577082f:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Jamgön Kongtrul
    8411333ccd4b485b875042d6e71f95fc:
      title: A Heart Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    328ec88d85884d03bc94fdc6e61797ce:
      title: A Prayer of Aspiration for the Mountain of Glory
      parent: Jamyang Khyentse Chökyi Lodrö
    b2c9b521b5e148029ab6e1274613684f:
      title: A Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    d8f92e51320845b296ec8688c074e20c:
      title: A Yearning Plea to the Precious Guru
      parent: Jamyang Khyentse Chökyi Lodrö
    ea77840af86c4597883b3145dab46d64:
      title: 'Cloud Banks of Blessings: A Prayer to Orgyen Rinpoche'
      parent: Jamyang Khyentse Chökyi Lodrö
    d06e1b52427c4f5c888cfd865ae88665:
      title: Prayer of the Wisdom Mind
      parent: Jamyang Khyentse Chökyi Lodrö
    d7c131e10ff84da79c0fcd1dcb8dd3f9:
      title: Spontaneous Fulfilment of Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    6ab1c40bae1b4436a965fcb875436c1b:
      title: The Falling Elixir of Blessing
      parent: Jamyang Khyentse Chökyi Lodrö
    e5976d1dc1d54f2a8b654d9f727fb334:
      title: 'The Fulfilment of Wishes and Aspirations: A Prayer to Ācārya Padmasambhava'
      parent: Jamyang Khyentse Chökyi Lodrö
    2ab5e5aea5d045c6bb76dbbe5230afb8:
      title: 'The Supreme Bestowal of Twofold Attainment: A Prayer to Orgyen Rinpoche,
        Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Chökyi Lodrö
    4a1b10a3ca6c48158d7c592e79c2c0e6:
      title: 'The Swift Fulfilment of Aspirations: A Prayer to Glorious Orgyen, King
        of Dharma'
      parent: Jamyang Khyentse Chökyi Lodrö
    2d636137c31e478ab72620b2f9a84ffb:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Jamyang Khyentse Chökyi Lodrö
    fd6a41911654418484ce68a6be0366ac:
      title: To Fulfil All Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    8d6d52baefa44ab3826a741100873585:
      title: Turning Back the Misfortunes of the Age of Degeneration
      parent: Jamyang Khyentse Chökyi Lodrö
    0f9fc144fad142a2b4c38c8b0a8b147d:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Jamyang Khyentse Wangpo
    b423b75484a04e2d9b8f053536f6ad37:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    5ad931f05a1c49768ebaf6b0e0bdab78:
      title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling
        to the Realm of Lotus Light'
      parent: Jamyang Khyentse Wangpo
    d216eab5b4154001bb581bcf53c1533b:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    f53108366919458ebf3cdbf8b72d9c0f:
      title: 'The Heart of Blessings: A Brief Anthology of Prayers to Guru Rinpoche
        and the Twenty-Five Disciples, the King and Subjects'
      parent: Jamyang Khyentse Wangpo
    17d47d54171e46dcacd7f2fc7ec79fe5:
      title: 'Turning Back Obstacles and Adverse Circumstances: A Prayer to Orgyen
        Rinpoche, Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Wangpo
    d330d8320d8f45a692292aad1f0ea35d:
      title: 'Wish-Fulfilling Feast of Siddhis: An Aspiration Prayer to Orgyen Rinpoche,
        the Precious Master of Oddiyana'
      parent: Jamyang Khyentse Wangpo
    0518ef8da1c044858d98b2f13a189222:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Jigme Lingpa
    2a7f78a59c784a76b687dcd478feac6f:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Jigme Lingpa
    122a2cd566a94ca5b5805a8db681f989:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    79a87e562efb464eb1538094e1d8653f:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Jigme Lingpa
    9d32044c0c07446884103540feb64c48:
      title: Prayer to Pema Tötreng Tsal
      parent: Khenchen Ngawang Palzang
    3cf0f63495f648af900ea23a64357da6:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Longchen Rabjam
    0e5cd44a9387434f982237bcd486c0c8:
      title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
      parent: Menlungpa Mikyö Dorje
    b983a906cdd24a6ca8d9dd934f5b6358:
      title: A Plaintive Prayer to Guru Rinpoche
      parent: Minling Chung Rinpoche
    bd1d952338fb4e7880d660da18d5ca89:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      parent: Mipham Rinpoche
    3817ec4813134fc2a8785dea875d348a:
      title: Recollecting the Deeds of The Tenth Days
      parent: Mipham Rinpoche
    22d5239f55e04e9cb5982d44af8ec7d1:
      title: The Prayer which is the Source of All True Realization
      parent: Mipham Rinpoche
    6dbf97ec98bc443f9399cd4895567045:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Mipham Rinpoche
    7801aca08bac4484b98ed83b3d6066e0:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    652d305ec911465eae1b226e4c1aa279:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    b0cb09329ac9422ab97f0122a147b125:
      title: The Prayer to Orgyen Rinpoche that Invokes the Heart of his Wisdom Mind
      parent: Pawo Lerab Tsal
    9216eadaf57e45f597253835316401cc:
      title: An Extremely Concise Barché Lamsel—The Prayer for Clearing Obstacles
        from the Path
      parent: Rangrik Dorje
    620a697b2e8b4111882f30623a218849:
      title: An Extremely Concise Sampa Lhundrup—Prayer that Spontaneously Fulfils
        All Wishes
      parent: Rangrik Dorje
    fd6f80bc11614efba4db4a46516303c3:
      title: The Seven Lines that Dispel All Obstacles and Enfold All Profundity
      parent: Rangrik Dorje
    2e292626e9334219992e418cfb0871fc:
      title: 'The Spontaneous Fulfilment of All Wishes: Invoking the Great Guru of
        Uḍḍiyāna'
      parent: Rangrik Dorje
    8346e9f9885d4ec2ae8a3b1455fd86da:
      title: 'The Wish-Fulfilling Tree: A Prayer to the All-Embodying Lama Tsokye
        Dorje'
      parent: Rangrik Dorje
    b20a5b116a9a4b539f590eec6a783898:
      title: 'Victory Over All Adversity: A Prayer to Invoke Guru Rinpoche’s Wisdom
        for the Swift Fulfilment of Wishes'
      parent: Rangrik Dorje
    4bfe0b6f9bdf43ffb5099a0292efd43b:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Ratna Lingpa
    860ae9ef941b4b6780f36912649c85c1:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Ratna Lingpa
    ff61c9cafe1647d1b1231d72efef4523:
      title: A Prayer To Padmasambhava
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    d514e1b3aa814fdab95bdce8e570d166:
      title: A Prayer to the Vajradhara of Oḍḍiyāna
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    a83e9c80886a4b0693a7293ea2cd9ecd:
      title: 'The Beat of the Vajra Drum: A Prayer'
      parent: Shechen Rabjam Rinpoche
    1ed297e999f348c0a587232f3e4cd7ec:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Outlines
created_at: '2022-03-01T03:50:02.056707'
last_modified_at: '2022-03-01T03:50:02.056710'
